services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    # environment:
    #   - DATABASE_HOST=${DATABASE_HOST}
    #   - DATABASE_PORT=${DATABASE_PORT}
    #   - DATABASE_USER=${DATABASE_USER}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - DATABASE_DB=${DATABASE_DB}
    #   - NODE_ENV=${NODE_ENV}
    depends_on:
      - postgres_db
    networks:
      - app-network

  postgres_db:
    image: postgres:alpine
    container_name: books-store-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
